version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/pretty-pdf
    binary: pretty-pdf
    ldflags:
      - -s -w
      - -X github.com/sazardev/go-pretty-pdf/cmd/pretty-pdf.version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz, zip]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^Merge "


checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"
